name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    container: gcr.io/k8s-skaffold/skaffold:v1.3.1
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Artifact
        uses: ./.github/workflows/skaffold
        with:
          registry: ghcr.io/liatrio
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
