name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Artifact
        uses: ./.github/workflows/skaffold
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
